HAI
	I HAS A X ITZ 5
	I HAS A Y ITZ 3

	BTW lezz tezz arithmetic
	SUM OF X AN Y
	VISIBLE IT
	DIFF OF X AN Y
	VISIBLE IT
	PRODUKT OF X AN Y
	VISIBLE IT
	QUOSHUNT OF X AN Y
	VISIBLE IT
	MOD OF X AN Y
	VISIBLE IT
	BIGGR OF X AN Y
	VISIBLE IT
	SMALLR OF X AN Y
	VISIBLE IT

	BTW lezz tezz arithmetic more
	I HAS A pen ITZ "5"
	I HAS A apple ITZ "5.0"

	SUM OF X AN pen
	VISIBLE IT
	SUM OF X AN apple
	VISIBLE IT
	SUM OF apple AN pen
	VISIBLE IT
	SUM OF PRODUKT OF X AN Y AN QUOSHUNT OF X AN pen
	VISIBLE IT

KTHXBYE