HAI
	I HAS A X
	I HAS A Y
	BTW lezz tezz boolean operations
	X R WIN
	Y R FAIL

	BOTH OF X AN X BTW WIN
	VISIBLE IT
	BOTH OF X AN Y BTW FAIL
	VISIBLE IT
	BOTH OF Y AN Y BTW FAIL
	VISIBLE IT
	
	EITHER OF X AN X BTW WIN
	VISIBLE IT
	EITHER OF X AN Y BTW WIN
	VISIBLE IT
	EITHER OF Y AN Y BTW FAIL
	VISIBLE IT

	WON OF X AN X BTW FAIL
	VISIBLE IT
	WON OF X AN Y BTW WIN
	VISIBLE IT
	WON OF Y AN Y BTW FAIL
	VISIBLE IT

	NOT X BTW FAIL
	VISIBLE IT
	NOT Y BTW WIN
	VISIBLE IT


	BTW lezz tezz bool ops more

	NOT BOTH OF X AN EITHER OF WON OF X AN Y AN X BTW WIN
	VISIBLE IT

	ALL OF NOT X AN BOTH OF Y AN X AN EITHER OF X AN Y MKAY BTW FAIL
	VISIBLE IT
	ANY OF NOT X AN BOTH OF Y AN X AN EITHER OF X AN Y MKAY BTW FAIL
	VISIBLE IT

KTHXBYE